export enum ErrorCodes {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  MISSING_REQUIRED_HEADERS = 'MISSING_REQUIRED_HEADERS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Auth & RBAC
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  USER_INACTIVE = 'USER_INACTIVE',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',

  // RBAC administration (roles/permissions CRUD)
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_ALREADY_EXISTS = 'ROLE_ALREADY_EXISTS',
  ROLE_HAS_ASSIGNED_USERS = 'ROLE_HAS_ASSIGNED_USERS',
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',
  PERMISSION_ALREADY_EXISTS = 'PERMISSION_ALREADY_EXISTS',
  ROLE_PERMISSION_NOT_ASSIGNED = 'ROLE_PERMISSION_NOT_ASSIGNED',

  // Idempotency
  MISSING_IDEMPOTENCY_KEY = 'MISSING_IDEMPOTENCY_KEY',
  IDEMPOTENT_REQUEST_IN_PROGRESS = 'IDEMPOTENT_REQUEST_IN_PROGRESS',

  // Identity (register/login/refresh)
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  // Business domain: catalog
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',

  // Business domain: paths & questionnaire
  INVALID_QUESTION_OPTION = 'INVALID_QUESTION_OPTION',
  PATH_NOT_FOUND = 'PATH_NOT_FOUND',

  // Persistence (Prisma P2025 mapped by GlobalExceptionFilter)
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
}
